### PR TITLE
Add support for multiple org

### LINKED ISSUE #30: Add support for multiple organizations

### PR DESCRIPTION
**Pull request by se7entyse7en**
Closes #30. Rebased on #49 because it reuses some functionalities already introduced in that PR.

With this PR the flow for the ghsync command is the following:
1. list of all repos for all orgs serially (no parallelization), exit on first error
2. download organizations in parallel, exit on first error by also stopping pending downloads,
3. download repos (of all organizations) in parallel, exit on first error by also stopping pending downloads.

The logic for parallelizing downloads in points 2 and 3 is the same.

An alternative way was to do the same 3 steps mentioned above, but once for each org, by reusing parallel repo downloads introduced in #49. However, this alternative it's not optimal. For example, if an org has a very large repo, then before going to the next organization the application would wait for that repo to finish with a single downloader being used and all the others waiting. On the other hand, this doesn't happen by parallelizing the download of all the repositories in a single batch.

---

* [ ] I have updated the CHANGELOG file according to the conventions in [keepachangelog.com](https://keepachangelog.com)
* [ ] This PR contains changes that do not require a mention in the CHANGELOG file

### CODE REVIEW

**Comment by smacker** [comment]
Did you think about changing `(c *Ghsync) Execute` by running `ExecuteBody` there in go-routines?

**Comment by se7entyse7en** [comment]
> Did you think about changing `(c *Ghsync) Execute` by running `ExecuteBody` there in go-routines?

I actually feel dump now 😂.
Initially, I thought that it won't work because it would make some clients to wait, but it's actually not true. It should definitely work, and moreover it would be damn much easier.

**Comment by se7entyse7en** [comment]
mhmmm... the bad thing is that as-is I think it's easier to have the overall progress, and also it may lead to having the same logic (about waitgroup, etc.) inside `downloadRepos` and in the `ExecuteBody`. wdyt?

**Comment by se7entyse7en** [comment]
> Though I think we are on the edge of complexity here and will have to change something if we add more logic. Way too many closures and functions with 6 params aren't nice.

I completely agree with you. The thing is that at this stage I prefer to not over-work this part mainly for the reason that if we decide to deploy CE with `metadata-retrieval` _not_ standalone, but with DR mother project (I still don't know how to call it properly), then this cli won't be used and will handle all of these differently.

If we'll decide to run this using this cli then yes. For sure there are things that we have to revise.

**Pull request merged**
